version: '3.7'

services:
  pg_db:
    image: postgres:12
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=shill
      - POSTGRES_USER=shiller
      - POSTGRES_DB=shill_db
    ports:
      - "5432:5432"
    expose:
      - 5432

  bot:
    build:
      context: ~/projects/shill-leader-bot
      dockerfile: Dockerfile
    image: result/latest
    env_file:
      - ~/projects/shill-leader-bot/test.env
    ports:
      - "8080:8080"
    depends_on: 
      - pg_db

  web:
    build:
      context: ~/projects/admin_panel/shill_admin_panel
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ~/projects/shill-leader-bot/test.env
    depends_on:
      - pg_db

volumes:
  postgres-data: